name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Next.js to Heroku
    runs-on: ubuntu-latest

    steps:
      # Checkout with full history
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build the App
      - name: Build Next.js App
        run: npm run build

      # Debug Heroku CLI
      - name: Debug Heroku CLI
        run: |
          heroku --version
          heroku auth:whoami

      # Add Heroku Remote
      - name: Add Heroku Remote
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      # Check Deployment Status
      - name: Check Heroku Logs
        run: |
          echo "Deployment complete! Check your Heroku app at https://$HEROKU_APP_NAME.herokuapp.com"