name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Triggers deployment on push to 'main'. Adjust if needed.

jobs:
  deploy:
    name: Deploy Next.js to Heroku
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a compatible Node.js version for your Next.js app

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Next.js Application
      - name: Build Next.js App
        run: npm run build

      # Step 5: Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      # Step 6: Check Deployment Status
      - name: Check Heroku Logs
        run: |
          echo "Deployment complete! Check your Heroku app at https://$HEROKU_APP_NAME.herokuapp.com"